### ISSUE TITLE
problem with static keyword

### ISSUE THREAD

**Issue by sozud** [mkst/mwccgap#3]
The static keyword seems to produce an error:

```
    function_name = function_names[len(self.functions)]
IndexError: list index out of range
```

To reproduce remove the `#ifdef` here
https://github.com/Xeeynamo/sotn-decomp/blob/fa3ba301c2214f962261663f4af526a5b1b38470/src/st/e_red_door.h#L14

**Comment by mkst** [comment]
A static function won't be exported, so I'll have to see if there's a workaround.. does the function have to be declared static?

**Comment by sozud** [comment]
@Xeeynamo we are marking things static due to conlicting symbols on the PC build right? What about something like
```
#ifdef VERSION_PC
#define STATIC static
#else
#define STATIC
#endif
```

**Comment by mkst** [comment]
Update mwccgap and created a [PR](https://github.com/Xeeynamo/sotn-decomp/pull/1311) for sotn. `static` functions have local symbol names, so I can still find them - this still gives an :ok: so seems to work - might need revisiting at a later date though.
